version: '3.8'

services:
  tomcat-app:
    build: .
    ports:
      - "8080:8080"  # Porta da aplicação
      - "9090:9090"  # Porta para métricas do Prometheus
    environment:
      - CATALINA_OPTS=-javaagent:/usr/local/tomcat/jmx_prometheus_javaagent.jar=9090:/usr/local/tomcat/config.yml

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"